[package]
name = "deptool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.15.2"
io = "0.0.2"
argparse = "0.2.2"
lazy_static = "1.4.0"
[workspace]
